services:
  - type: web
    name: phan-mem-quan-ly-khoa-ntk
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
